### PR TITLE
Add ReadBox trait

### PR DESCRIPTION
**Pull request by ian-spoonradio**

### CODE REVIEW

**Comment by alfg** [comment]
Hi @ian-spoonradio, 

Thanks for the PR. Is it possible to add some context of this PR for reference?

Thank you.

**Comment by ian-spoonradio** [comment]
Hi @alfg

I’m sorry but I’m not sure that I understand.
Could you be more specific?

**Comment by alfg** [comment]
Hi @ian-spoonradio,

Just a description and reasoning for the PR.

**Comment by ian-spoonradio** [comment]
https://doc.rust-lang.org/book/ch10-02-traits.html

> A type’s behavior consists of the methods we can call on that type. Different types share the same behavior if we can call the same methods on all of those types. Trait definitions are a way to group method signatures together to define a set of behaviors necessary to accomplish some purpose.

All box types share the same behavior of `read-box()`. We only need to call `BoxType::read_box()` instead of individual functions.

**Comment by alfg** [comment]
Great. Thank you! I will test this out and merge later tonight.

**Comment by alfg** [comment]
Thanks @ian-spoonradio!

**Pull request merged**
